; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Conditional and unconditional branches, and an indirect branch.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

declare void @sink(i64)

define void @cond_br(i64 %a, i64 %b) {
; CHECK-LABEL: cond_br#
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,1,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    cmp.ge p6, p0 = r32, r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) brl.cond.sptk .LBB0_2
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    adds out0 = 1, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_3
; CHECK-NEXT:  .LBB0_2: // %else
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 2, r0
; CHECK-NEXT:  .LBB0_3: // %exit
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = sink#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp cond_br#
entry:
  %c = icmp slt i64 %a, %b
  br i1 %c, label %then, label %else
then:
  call void @sink(i64 1)
  br label %exit
else:
  call void @sink(i64 2)
  br label %exit
exit:
  ret void
}

define i64 @loop(i64 %n) {
; CHECK-LABEL: loop#
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r3 = r8
; CHECK-NEXT:  .LBB1_1: // %head
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    add r8 = r8, r3
; CHECK-NEXT:    adds r3 = 1, r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmp.lt p6, p0 = r3, r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) brl.cond.sptk .LBB1_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp loop#
entry:
  br label %head
head:
  %i = phi i64 [ 0, %entry ], [ %i.next, %head ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %head ]
  %acc.next = add i64 %acc, %i
  %i.next = add i64 %i, 1
  %c = icmp slt i64 %i.next, %n
  br i1 %c, label %head, label %exit
exit:
  ret i64 %acc.next
}

define void @indirect_br(ptr %addr) {
; CHECK-LABEL: indirect_br#
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,3,1,0
; CHECK-NEXT:    .save rp, r34
; CHECK-NEXT:    mov r34 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov b6 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p0) br.cond.sptk b6
; CHECK-NEXT:  .LBB2_1: // %a
; CHECK-NEXT:    adds out0 = 10, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB2_2
; CHECK-NEXT:  .LBB2_3: // %b
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 20, r0
; CHECK-NEXT:  .LBB2_2: // %a
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = sink#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp indirect_br#
entry:
  indirectbr ptr %addr, [ label %a, label %b ]
a:
  call void @sink(i64 10)
  ret void
b:
  call void @sink(i64 20)
  ret void
}
