; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Integer division and remainder are provided by the toolchain runtime
; (libgcc) rather than a native instruction, so these become library calls.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define i64 @sdiv_i64(i64 %a, i64 %b) {
; CHECK-LABEL: sdiv_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __divdi3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp sdiv_i64#
  %r = sdiv i64 %a, %b
  ret i64 %r
}

define i64 @udiv_i64(i64 %a, i64 %b) {
; CHECK-LABEL: udiv_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __udivdi3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp udiv_i64#
  %r = udiv i64 %a, %b
  ret i64 %r
}

define i64 @srem_i64(i64 %a, i64 %b) {
; CHECK-LABEL: srem_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __moddi3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp srem_i64#
  %r = srem i64 %a, %b
  ret i64 %r
}

define i64 @urem_i64(i64 %a, i64 %b) {
; CHECK-LABEL: urem_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __umoddi3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp urem_i64#
  %r = urem i64 %a, %b
  ret i64 %r
}
