; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Integer sign/zero/any extension and truncation, including the i1 <-> GR
; conversions used for predicate values.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define i64 @sext_i32_i64(i32 %a) {
; CHECK-LABEL: sext_i32_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    sxt4 r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp sext_i32_i64#
  %r = sext i32 %a to i64
  ret i64 %r
}

define i64 @zext_i32_i64(i32 %a) {
; CHECK-LABEL: zext_i32_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    zxt4 r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp zext_i32_i64#
  %r = zext i32 %a to i64
  ret i64 %r
}

define i64 @sext_i16_i64(i16 %a) {
; CHECK-LABEL: sext_i16_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    sxt2 r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp sext_i16_i64#
  %r = sext i16 %a to i64
  ret i64 %r
}

define i64 @zext_i8_i64(i8 %a) {
; CHECK-LABEL: zext_i8_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    zxt1 r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp zext_i8_i64#
  %r = zext i8 %a to i64
  ret i64 %r
}

define i32 @trunc_i64_i32(i64 %a) {
; CHECK-LABEL: trunc_i64_i32#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp trunc_i64_i32#
  %r = trunc i64 %a to i32
  ret i32 %r
}

define i64 @zext_i1_i64(i1 %a) {
; CHECK-LABEL: zext_i1_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    adds r3 = 1, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    and r8 = r32, r3
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp zext_i1_i64#
  %r = zext i1 %a to i64
  ret i64 %r
}

define i64 @sext_i1_i64(i1 %a) {
; CHECK-LABEL: sext_i1_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    adds r3 = 1, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    and r3 = r32, r3
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sub r8 = r8, r3
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp sext_i1_i64#
  %r = sext i1 %a to i64
  ret i64 %r
}
