; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Native 80-bit floating point (x86_fp80 / long double): full-precision
; arithmetic, the two-slot memory layout (ldfe/stfe), and constant pool loads.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define x86_fp80 @add_f80(x86_fp80 %a, x86_fp80 %b) {
; CHECK-LABEL: add_f80#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r32
; CHECK-NEXT:    alloc r32 = ar.pfs,0,1,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    fadd f8 = f8, f9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp add_f80#
  %r = fadd x86_fp80 %a, %b
  ret x86_fp80 %r
}

define x86_fp80 @load_f80(ptr %p) {
; CHECK-LABEL: load_f80#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    ldfe f8 = [r32]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp load_f80#
  %v = load x86_fp80, ptr %p
  ret x86_fp80 %v
}

define void @store_f80(x86_fp80 %v, ptr %p) {
; CHECK-LABEL: store_f80#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r35
; CHECK-NEXT:    alloc r35 = ar.pfs,0,4,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    stfe [r34] = f8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp store_f80#
  store x86_fp80 %v, ptr %p
  ret void
}

define x86_fp80 @const_f80() {
; CHECK-LABEL: const_f80#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r32
; CHECK-NEXT:    alloc r32 = ar.pfs,0,1,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    addl r3 = @ltoff(.LCPI3_0), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r3 = [r3]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ldfe f8 = [r3]
; CHECK-NEXT:    mov ar.pfs = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp const_f80#
  ret x86_fp80 0xK4000C90FDAA22168C235
}
