; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; The prologue of a frame-pointer function saves the old FP (r5) at
; [r12+16, r12+24), above the 16-byte scratch area at [r12, r12+16) that the
; psABI lets any callee clobber, so the call below cannot destroy the saved
; FP before the epilogue restores it.

declare void @use(ptr)

define i64 @fp_scratch(i64 %n) {
; CHECK-LABEL: fp_scratch#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,3,1,0
; CHECK-NEXT:    .save rp, r34
; CHECK-NEXT:    mov r34 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    add r22 = 16, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    st8 [r22] = r5
; CHECK-NEXT:    mov r5 = r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    adds r3 = 15, r32
; CHECK-NEXT:    adds r8 = -16, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    and r3 = r3, r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sub r3 = r12, r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r12 = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    add r12 = -16, r12
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    mov out0 = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = use#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    add r12 = 16, r12
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    add r22 = 16, r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r12 = r5
; CHECK-NEXT:    ld8 r5 = [r22]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp fp_scratch#
  %p = alloca i8, i64 %n
  call void @use(ptr %p)
  ret i64 0
}
