; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Global address materialization through the GOT (@ltoff) and load/store of a
; global's value.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

@g = global i64 0
@arr = global [4 x i64] zeroinitializer

define ptr @addr_of_g() {
; CHECK-LABEL: addr_of_g#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r3
; CHECK-NEXT:    alloc r3 = ar.pfs,0,0,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    // PSEUDO_ALLOC
; CHECK-NEXT:    addl r8 = @ltoff(g#), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    mov ar.pfs = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp addr_of_g#
  ret ptr @g
}

define i64 @load_g() {
; CHECK-LABEL: load_g#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r3
; CHECK-NEXT:    alloc r3 = ar.pfs,0,0,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    // PSEUDO_ALLOC
; CHECK-NEXT:    addl r8 = @ltoff(g#), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    mov ar.pfs = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp load_g#
  %v = load i64, ptr @g
  ret i64 %v
}

define void @store_g(i64 %v) {
; CHECK-LABEL: store_g#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r3
; CHECK-NEXT:    alloc r3 = ar.pfs,0,1,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    // PSEUDO_ALLOC
; CHECK-NEXT:    addl r8 = @ltoff(g#), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    st8 [r8] = r32
; CHECK-NEXT:    mov ar.pfs = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp store_g#
  store i64 %v, ptr @g
  ret void
}

define ptr @addr_of_elem() {
; CHECK-LABEL: addr_of_elem#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r3
; CHECK-NEXT:    alloc r3 = ar.pfs,0,0,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    // PSEUDO_ALLOC
; CHECK-NEXT:    addl r8 = @ltoff(arr#), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds r8 = 16, r8
; CHECK-NEXT:    mov ar.pfs = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp addr_of_elem#
  ret ptr getelementptr inbounds ([4 x i64], ptr @arr, i64 0, i64 2)
}
