; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Calls through a function pointer go via a function descriptor (entry point +
; gp) and branch through a branch register; the address of a function yields
; its @fptr descriptor.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

declare void @target()

define void @call_fp(ptr %fp) {
; CHECK-LABEL: call_fp#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .save rp, r34
; CHECK-NEXT:    mov r34 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    ld8 r3 = [r32]
; CHECK-NEXT:    adds r8 = 8, r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r8
; CHECK-NEXT:    mov b6 = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = b6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp call_fp#
  call void %fp()
  ret void
}

define i64 @call_fp_ret(ptr %fp, i64 %a) {
; CHECK-LABEL: call_fp_ret#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,1,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out0 = r33
; CHECK-NEXT:    ld8 r3 = [r32]
; CHECK-NEXT:    adds r8 = 8, r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r8
; CHECK-NEXT:    mov b6 = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = b6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp call_fp_ret#
  %r = call i64 %fp(i64 %a)
  ret i64 %r
}

define ptr @func_addr() {
; CHECK-LABEL: func_addr#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r32
; CHECK-NEXT:    alloc r32 = ar.pfs,0,1,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    addl r3 = @ltoff(@fptr(target#)), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r3]
; CHECK-NEXT:    mov ar.pfs = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp func_addr#
  ret ptr @target
}
