; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; A dense switch is lowered through an (absolute) jump table.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

declare void @sink(i64)

define void @jt(i64 %x) {
; CHECK-LABEL: jt#
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,3,1,0
; CHECK-NEXT:    .save rp, r34
; CHECK-NEXT:    mov r34 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    adds r3 = 4, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmp.gtu p6, p0 = r32, r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) brl.cond.sptk .LBB0_8
; CHECK-NEXT:  // %bb.1: // %entry
; CHECK-NEXT:    adds r3 = 3, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    shl r3 = r32, r3
; CHECK-NEXT:    addl r8 = @ltoff(.LJTI0_0), r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    add r3 = r8, r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r3 = [r3]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov b6 = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p0) br.cond.sptk b6
; CHECK-NEXT:  .LBB0_2: // %c0
; CHECK-NEXT:    adds out0 = 10, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_3
; CHECK-NEXT:  .LBB0_7: // %c4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 14, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_3
; CHECK-NEXT:  .LBB0_5: // %c2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 12, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_3
; CHECK-NEXT:  .LBB0_6: // %c3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 13, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_3
; CHECK-NEXT:  .LBB0_4: // %c1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 11, r0
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_3
; CHECK-NEXT:  .LBB0_8: // %def
; CHECK-NEXT:    ;;
; CHECK-NEXT:    adds out0 = 99, r0
; CHECK-NEXT:  .LBB0_3: // %c0
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = sink#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp jt#
entry:
  switch i64 %x, label %def [
    i64 0, label %c0
    i64 1, label %c1
    i64 2, label %c2
    i64 3, label %c3
    i64 4, label %c4
  ]
c0:
  call void @sink(i64 10)
  ret void
c1:
  call void @sink(i64 11)
  ret void
c2:
  call void @sink(i64 12)
  ret void
c3:
  call void @sink(i64 13)
  ret void
c4:
  call void @sink(i64 14)
  ret void
def:
  call void @sink(i64 99)
  ret void
}
