; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Multiplication (via the XMA unit) and the high-half / wide multiplies, plus
; population count.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define i64 @mul_i64(i64 %a, i64 %b) {
; CHECK-LABEL: mul_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    setf.sig f6 = r33
; CHECK-NEXT:    setf.sig f7 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    xma.l f6 = f7, f6, f0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    getf.sig r8 = f6
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp mul_i64#
  %r = mul i64 %a, %b
  ret i64 %r
}

define i64 @mulhu_i64(i64 %a, i64 %b) {
; CHECK-LABEL: mulhu_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    setf.sig f6 = r33
; CHECK-NEXT:    setf.sig f7 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    xma.hu f6 = f7, f6, f0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    getf.sig r8 = f6
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp mulhu_i64#
  %za = zext i64 %a to i128
  %zb = zext i64 %b to i128
  %m = mul i128 %za, %zb
  %s = lshr i128 %m, 64
  %r = trunc i128 %s to i64
  ret i64 %r
}

define i64 @mulhs_i64(i64 %a, i64 %b) {
; CHECK-LABEL: mulhs_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    setf.sig f6 = r33
; CHECK-NEXT:    setf.sig f7 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    xma.h f6 = f7, f6, f0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    getf.sig r8 = f6
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp mulhs_i64#
  %sa = sext i64 %a to i128
  %sb = sext i64 %b to i128
  %m = mul i128 %sa, %sb
  %s = lshr i128 %m, 64
  %r = trunc i128 %s to i64
  ret i64 %r
}

define i32 @mul_i32(i32 %a, i32 %b) {
; CHECK-LABEL: mul_i32#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    setf.sig f6 = r33
; CHECK-NEXT:    setf.sig f7 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    xma.l f6 = f7, f6, f0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    getf.sig r8 = f6
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp mul_i32#
  %r = mul i32 %a, %b
  ret i32 %r
}

define i64 @popcnt_i64(i64 %a) {
; CHECK-LABEL: popcnt_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,2,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    popcnt r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp popcnt_i64#
  %r = call i64 @llvm.ctpop.i64(i64 %a)
  ret i64 %r
}

declare i64 @llvm.ctpop.i64(i64)
