; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Like returns-twice-spill.ll, but calling the returns_twice function
; indirectly. Values live across a returns_twice call must not be kept in
; stacked registers (r32-r127), because the second return (longjmp/vfork)
; may see a clobbered RSE backing store.

define i64 @indirect_returns_twice(ptr %fp, i64 %v) {
; CHECK-LABEL: indirect_returns_twice#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,0,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 64
; CHECK-NEXT:    add r12 = -64, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .body
; CHECK-NEXT:    add r22 = 56, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    st8 [r22] = r4
; CHECK-NEXT:    add r22 = 48, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    st8 [r22] = r6
; CHECK-NEXT:    add r22 = 40, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    st8 [r22] = r7
; CHECK-NEXT:    add r22 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    st8 [r22] = r33
; CHECK-NEXT:    ld8 r3 = [r32]
; CHECK-NEXT:    adds r8 = 8, r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r8 = [r8]
; CHECK-NEXT:    mov r4 = r1
; CHECK-NEXT:    mov r6 = r12
; CHECK-NEXT:    mov r7 = rp
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r8
; CHECK-NEXT:    mov b6 = r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = b6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r4
; CHECK-NEXT:    mov r12 = r6
; CHECK-NEXT:    mov rp = r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    add r22 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r3 = [r22]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    add r8 = r8, r3
; CHECK-NEXT:    add r22 = 40, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r7 = [r22]
; CHECK-NEXT:    add r22 = 48, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r6 = [r22]
; CHECK-NEXT:    add r22 = 56, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld8 r4 = [r22]
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 64, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp indirect_returns_twice#
  %r = call i64 %fp() returns_twice
  %s = add i64 %r, %v
  ret i64 %s
}
