; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Integer select and select-with-comparison.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define i64 @select_i64(i1 %c, i64 %a, i64 %b) {
; CHECK-LABEL: select_i64#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r35
; CHECK-NEXT:    alloc r35 = ar.pfs,0,4,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov r8 = r34
; CHECK-NEXT:    extr.u r3 = r32, 0, 1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmp.ne p6, p0 = r3, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) mov r8 = r33
; CHECK-NEXT:    mov ar.pfs = r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp select_i64#
  %r = select i1 %c, i64 %a, i64 %b
  ret i64 %r
}

define i64 @select_cc(i64 %x, i64 %y, i64 %a, i64 %b) {
; CHECK-LABEL: select_cc#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r36
; CHECK-NEXT:    alloc r36 = ar.pfs,0,5,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov r8 = r35
; CHECK-NEXT:    cmp.lt p6, p0 = r32, r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) mov r8 = r34
; CHECK-NEXT:    mov ar.pfs = r36
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp select_cc#
  %c = icmp slt i64 %x, %y
  %r = select i1 %c, i64 %a, i64 %b
  ret i64 %r
}
