; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Integer comparisons. The result is computed into a predicate register and
; materialized back into a GR for the i32 zext return.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define i32 @cmp_eq(i64 %a, i64 %b) {
; CHECK-LABEL: cmp_eq#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    cmp.eq p6, p0 = r32, r33
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) adds r8 = 1, r8
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp cmp_eq#
  %c = icmp eq i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @cmp_ne(i64 %a, i64 %b) {
; CHECK-LABEL: cmp_ne#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    cmp.ne p6, p0 = r32, r33
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) adds r8 = 1, r8
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp cmp_ne#
  %c = icmp ne i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @cmp_slt(i64 %a, i64 %b) {
; CHECK-LABEL: cmp_slt#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    cmp.lt p6, p0 = r32, r33
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) adds r8 = 1, r8
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp cmp_slt#
  %c = icmp slt i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @cmp_ult(i64 %a, i64 %b) {
; CHECK-LABEL: cmp_ult#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    cmp.ltu p6, p0 = r32, r33
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) adds r8 = 1, r8
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp cmp_ult#
  %c = icmp ult i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @cmp_sgt(i64 %a, i64 %b) {
; CHECK-LABEL: cmp_sgt#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    cmp.gt p6, p0 = r32, r33
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) adds r8 = 1, r8
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp cmp_sgt#
  %c = icmp sgt i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}
