; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; IA-64 has no 128-bit shift instruction. 128-bit shifts legalize to
; {SHL,SRA,SRL}_PARTS over an i64 register pair, which we mark Expand so the
; integer legalizer emits the libgcc libcall (__ashlti3/__ashrti3/__lshrti3),
; matching how 128-bit divide/modulo are handled.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

define i128 @shl_i128(i128 %a, i128 %b) {
; CHECK-LABEL: shl_i128#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r35
; CHECK-NEXT:    alloc r35 = ar.pfs,0,5,3,0
; CHECK-NEXT:    .save rp, r36
; CHECK-NEXT:    mov r36 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    zxt4 out2 = r34
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    mov r33 = rp
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __ashlti3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov rp = r33
; CHECK-NEXT:    mov ar.pfs = r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov rp = r36
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp shl_i128#
  %r = shl i128 %a, %b
  ret i128 %r
}

define i128 @ashr_i128(i128 %a, i128 %b) {
; CHECK-LABEL: ashr_i128#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r35
; CHECK-NEXT:    alloc r35 = ar.pfs,0,5,3,0
; CHECK-NEXT:    .save rp, r36
; CHECK-NEXT:    mov r36 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    sxt4 out2 = r34
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    mov r33 = rp
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __ashrti3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov rp = r33
; CHECK-NEXT:    mov ar.pfs = r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov rp = r36
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp ashr_i128#
  %r = ashr i128 %a, %b
  ret i128 %r
}

define i128 @lshr_i128(i128 %a, i128 %b) {
; CHECK-LABEL: lshr_i128#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r35
; CHECK-NEXT:    alloc r35 = ar.pfs,0,5,3,0
; CHECK-NEXT:    .save rp, r36
; CHECK-NEXT:    mov r36 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    zxt4 out2 = r34
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    mov r33 = rp
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __lshrti3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov rp = r33
; CHECK-NEXT:    mov ar.pfs = r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov rp = r36
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp lshr_i128#
  %r = lshr i128 %a, %b
  ret i128 %r
}
