; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; Small aggregates passed and returned by value: the IA-64 ABI flattens them
; into the argument registers / return registers.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

%struct.two = type { i64, i64 }

define i64 @pass_struct(%struct.two %s) {
; CHECK-LABEL: pass_struct#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    add r8 = r32, r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp pass_struct#
  %a = extractvalue %struct.two %s, 0
  %b = extractvalue %struct.two %s, 1
  %r = add i64 %a, %b
  ret i64 %r
}

define %struct.two @ret_struct(i64 %a, i64 %b) {
; CHECK-LABEL: ret_struct#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov r9 = r33
; CHECK-NEXT:    mov r8 = r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp ret_struct#
  %s0 = insertvalue %struct.two undef, i64 %a, 0
  %s1 = insertvalue %struct.two %s0, i64 %b, 1
  ret %struct.two %s1
}

declare i64 @take(%struct.two)

define i64 @call_struct(i64 %a, i64 %b) {
; CHECK-LABEL: call_struct#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = take#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp call_struct#
  %s0 = insertvalue %struct.two undef, i64 %a, 0
  %s1 = insertvalue %struct.two %s0, i64 %b, 1
  %r = call i64 @take(%struct.two %s1)
  ret i64 %r
}
