; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ia64 < %s | FileCheck %s --check-prefix=STATIC
; RUN: llc -mtriple=ia64 -relocation-model=pic < %s | FileCheck %s --check-prefix=PIC

; Thread-local storage. Under the static relocation model a local TLS symbol
; uses Local-Exec (movl @tprel) and an external one uses Initial-Exec
; (@ltoff(@tprel) via the GOT); under PIC both use General-Dynamic
; (@dtpmod/@dtprel + a call to __tls_get_addr). r13 is the thread pointer.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

@ext_tls = external thread_local global i64
@loc_tls = internal thread_local global i64 0

define ptr @addr_ext() {
; STATIC-LABEL: addr_ext#
; STATIC:       // %bb.0:
; STATIC-NEXT:    .prologue
; STATIC-NEXT:    .save ar.pfs, r32
; STATIC-NEXT:    alloc r32 = ar.pfs,0,1,0,0
; STATIC-NEXT:    .body
; STATIC-NEXT:    addl r3 = @ltoff(@tprel(ext_tls#)), r1
; STATIC-NEXT:    ;;
; STATIC-NEXT:    ld8 r3 = [r3]
; STATIC-NEXT:    ;;
; STATIC-NEXT:    add r8 = r13, r3
; STATIC-NEXT:    mov ar.pfs = r32
; STATIC-NEXT:    ;;
; STATIC-NEXT:    br.ret.sptk.many rp
; STATIC-NEXT:    .endp addr_ext#
;
; PIC-LABEL: addr_ext#
; PIC:       // %bb.0:
; PIC-NEXT:    .prologue
; PIC-NEXT:    .save ar.pfs, r34
; PIC-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; PIC-NEXT:    .save rp, r35
; PIC-NEXT:    mov r35 = rp
; PIC-NEXT:    .fframe 32
; PIC-NEXT:    add r12 = -32, r12
; PIC-NEXT:    .body
; PIC-NEXT:    addl r3 = @ltoff(@dtpmod(ext_tls#)), r1
; PIC-NEXT:    ;;
; PIC-NEXT:    ld8 out0 = [r3]
; PIC-NEXT:    addl r3 = @ltoff(@dtprel(ext_tls#)), r1
; PIC-NEXT:    ;;
; PIC-NEXT:    ld8 out1 = [r3]
; PIC-NEXT:    mov r32 = r1
; PIC-NEXT:    mov r33 = rp
; PIC-NEXT:    ;;
; PIC-NEXT:    br.call.sptk rp = __tls_get_addr#
; PIC-NEXT:    ;;
; PIC-NEXT:    mov r1 = r32
; PIC-NEXT:    mov rp = r33
; PIC-NEXT:    mov ar.pfs = r34
; PIC-NEXT:    ;;
; PIC-NEXT:    mov rp = r35
; PIC-NEXT:    .restore sp
; PIC-NEXT:    add r12 = 32, r12
; PIC-NEXT:    ;;
; PIC-NEXT:    br.ret.sptk.many rp
; PIC-NEXT:    .endp addr_ext#
  ret ptr @ext_tls
}

define ptr @addr_loc() {
; STATIC-LABEL: addr_loc#
; STATIC:       // %bb.0:
; STATIC-NEXT:    .prologue
; STATIC-NEXT:    .save ar.pfs, r32
; STATIC-NEXT:    alloc r32 = ar.pfs,0,1,0,0
; STATIC-NEXT:    .body
; STATIC-NEXT:    movl r3 = @tprel(loc_tls#)
; STATIC-NEXT:    ;;
; STATIC-NEXT:    add r8 = r13, r3
; STATIC-NEXT:    mov ar.pfs = r32
; STATIC-NEXT:    ;;
; STATIC-NEXT:    br.ret.sptk.many rp
; STATIC-NEXT:    .endp addr_loc#
;
; PIC-LABEL: addr_loc#
; PIC:       // %bb.0:
; PIC-NEXT:    .prologue
; PIC-NEXT:    .save ar.pfs, r34
; PIC-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; PIC-NEXT:    .save rp, r35
; PIC-NEXT:    mov r35 = rp
; PIC-NEXT:    .fframe 32
; PIC-NEXT:    add r12 = -32, r12
; PIC-NEXT:    .body
; PIC-NEXT:    addl r3 = @ltoff(@dtpmod(loc_tls#)), r1
; PIC-NEXT:    ;;
; PIC-NEXT:    ld8 out0 = [r3]
; PIC-NEXT:    addl r3 = @ltoff(@dtprel(loc_tls#)), r1
; PIC-NEXT:    ;;
; PIC-NEXT:    ld8 out1 = [r3]
; PIC-NEXT:    mov r32 = r1
; PIC-NEXT:    mov r33 = rp
; PIC-NEXT:    ;;
; PIC-NEXT:    br.call.sptk rp = __tls_get_addr#
; PIC-NEXT:    ;;
; PIC-NEXT:    mov r1 = r32
; PIC-NEXT:    mov rp = r33
; PIC-NEXT:    mov ar.pfs = r34
; PIC-NEXT:    ;;
; PIC-NEXT:    mov rp = r35
; PIC-NEXT:    .restore sp
; PIC-NEXT:    add r12 = 32, r12
; PIC-NEXT:    ;;
; PIC-NEXT:    br.ret.sptk.many rp
; PIC-NEXT:    .endp addr_loc#
  ret ptr @loc_tls
}
