; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ia64 -enable-tail-merge=false < %s | FileCheck %s

; A framed function with more than one epilogue needs '.label_state' after
; '.body' and '.copy_state' before each '.restore sp', so GNU as does not reject
; the second '.restore' (its unwind region was closed by the first). Tail-merge
; is disabled here to keep the two epilogues from being folded into one.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

declare void @ext1(i32)

define void @multi_epilogue(i32 %x) {
; CHECK-LABEL: multi_epilogue#
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,3,1,0
; CHECK-NEXT:    .save rp, r34
; CHECK-NEXT:    mov r34 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    .label_state 1
; CHECK-NEXT:    zxt4 r3 = r32
; CHECK-NEXT:    adds r8 = 0, r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmp.ne p6, p0 = r3, r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    (p6) brl.cond.sptk .LBB0_2
; CHECK-NEXT:    (p0) brl.cond.sptk .LBB0_1
; CHECK-NEXT:  .LBB0_2: // %b
; CHECK-NEXT:    adds out0 = 22, r0
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = ext1#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    .copy_state 1
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:  .LBB0_1: // %a
; CHECK-NEXT:    adds out0 = 11, r0
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = ext1#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    .copy_state 1
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp multi_epilogue#
entry:
  %c = icmp eq i32 %x, 0
  br i1 %c, label %a, label %b
a:
  call void @ext1(i32 11)
  ret void
b:
  call void @ext1(i32 22)
  ret void
}
