; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=ia64 < %s | FileCheck %s

; IA-64 native stack-unwind directives (.proc / .prologue / .save ar.pfs /
; .save rp / .fframe / .body / .restore sp / .endp). GNU as assembles these into
; the .IA_64.unwind / .IA_64.unwind_info sections that gdb/libunwind read to walk
; the stack, so they are what makes a backtrace step past a frame. The key record
; is '.save rp, <reg>': a non-leaf function parks its return pointer in a fixed
; stacked local that the unwinder can name from anywhere in the body.

target datalayout = "e-m:e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "ia64"

declare void @ext()

; A leaf function never clobbers b0: no '.save rp', no frame.
define i64 @leaf(i64 %a, i64 %b) {
; CHECK-LABEL: leaf#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .body
; CHECK-NEXT:    add r8 = r32, r33
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp leaf#
  %r = add i64 %a, %b
  ret i64 %r
}

; A non-leaf function parks rp in a stacked local: '.save rp, <reg>' with the
; matching 'mov <reg> = rp' in the prologue and the restore before the return.
define void @nonleaf() {
; CHECK-LABEL: nonleaf#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r33
; CHECK-NEXT:    alloc r33 = ar.pfs,0,3,0,0
; CHECK-NEXT:    .save rp, r34
; CHECK-NEXT:    mov r34 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = ext#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r33
; CHECK-NEXT:    mov rp = r34
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp nonleaf#
  call void @ext()
  ret void
}

; A function whose only call is a libcall (sdiv -> __divdi3) is still non-leaf:
; hasCalls() sees it even though there is no call at the IR level, so rp is
; parked and '.save rp' is emitted.
define i64 @libcall(i64 %a, i64 %b) {
; CHECK-LABEL: libcall#
; CHECK:       // %bb.0:
; CHECK-NEXT:    .prologue
; CHECK-NEXT:    .save ar.pfs, r34
; CHECK-NEXT:    alloc r34 = ar.pfs,0,4,2,0
; CHECK-NEXT:    .save rp, r35
; CHECK-NEXT:    mov r35 = rp
; CHECK-NEXT:    .fframe 32
; CHECK-NEXT:    add r12 = -32, r12
; CHECK-NEXT:    .body
; CHECK-NEXT:    mov out1 = r33
; CHECK-NEXT:    mov out0 = r32
; CHECK-NEXT:    mov r32 = r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.call.sptk rp = __divdi3#
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mov r1 = r32
; CHECK-NEXT:    mov ar.pfs = r34
; CHECK-NEXT:    mov rp = r35
; CHECK-NEXT:    .restore sp
; CHECK-NEXT:    add r12 = 32, r12
; CHECK-NEXT:    ;;
; CHECK-NEXT:    br.ret.sptk.many rp
; CHECK-NEXT:    .endp libcall#
  %r = sdiv i64 %a, %b
  ret i64 %r
}
